config/routes.rb
Rails.application.routes.draw do
  root 'parking_areas#index'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  # resources :users, only: [:show, :edit, :update]
  resources :parking_areas do
    resources :verifications, only: [:create, :update]
    resources :reviews, except: [:show, :index]
    post 'redirect_to_new_from_map', on: :collection
  end

  resources :reviews, only: [] do
    resources :comments, except: [:show, :index]
    resources :votes, only: [] do
      collection do
        post 'upvote'
        post 'downvote'
      end
    end
  end
end

app/views/infowindows/_index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>
    <div class="infowindow-content">
      <div class="row">
        <ul class="tabs" data-tabs id="marker-tabs">
          <li class="small-6 columns tabs-title"><a onclick="selectParkingInfoTab(<%= parking_area.id %>)" id="info-tab-<%= parking_area.id %>" aria-selected="true">Info</a></li>
          <li class="small-6 columns tabs-title"><a onclick="selectReviewsTab(<%= parking_area.id %>)" id="reviews-tab-<%= parking_area.id %>" aria-selected="false">Reviews</a></li>
        </ul>
      </div>

      <div class="tabs-content" data-tabs-content="marker-tabs">
        <div class="tabs-panel is-active" id="parking-info-<%= parking_area.id %>">
          <div class="row">
            <h5 style="text-align: center;" class="small-12 columns"><%= parking_area.title %></h5>
          </div>
          <div class="row">
            <input class="button round directions small-12 columns" type="button" value="Directions" onclick="calcRoute(<%= parking_area.latitude %>, <%= parking_area.longitude %>);">
            <input class="button round open-in-maps small-12 columns" type="button" value="Open in Maps" onclick="location.href='http://maps.apple.com/?q=<%= parking_area.latitude %>,<%= parking_area.longitude %>'">
          </div>

          <div class="row">
            <% if parking_area.verified? %>
              <h7 class="verified small-6 columns">Community Verified</h7>
            <% else %>
              <h7 class="unverified small-6 columns">Not Yet Verified</h7>
            <% end %>

            <% if verification && verification.value == 1 %>
              <p class="small-6 columns"><%= link_to "Remove Verification", parking_area_verification_path(parking_area_id: parking_area, id: verification.id), method: :patch %></p>
            <% elsif verification && verification.value == 0 %>
              <p class="small-6 columns"><%= link_to "Add Verification", parking_area_verification_path(parking_area_id: parking_area, id: verification.id), method: :patch %></p>
            <% else %>
              <p class="small-6 columns"><%= link_to "Add Verification", parking_area_verifications_path(parking_area), method: :post %></p>
            <% end %>
          </div>

          <div class="row">
            <p class="small-12 columns description-text"><%= parking_area.description %></p>
          </div>
          <div class='row'>
            <% if current_user && (parking_area.user == current_user || current_user.admin) %>
              <p class='small-4 columns'><%= link_to 'Show', parking_area %></p>
              <p class='small-3 columns'><%= link_to 'Edit', edit_parking_area_path(parking_area) %></p>
              <p class='small-5 columns'><%= link_to 'Destroy', parking_area, method: :delete, data: { confirm: 'Are you sure?' } %></p>
            <% else %>
              <p class='small-4 columns' style="float:right;"><%= link_to 'Show', parking_area %></p>
            <% end %>
          </div>
        </div>

        <div class="tabs-panel" id="reviews-<%= parking_area.id %>">
          <% unless reviews.empty? %>
            <% reviews.each do |review| %>
            <div class="review-area">
              <div class="row">
                <div class="rating small-8 columns">
                  <% i = 0 %>
                  <% 5.times do %>
                    <% if review.quality && i < review.quality %>
                      <%= image_tag("star-on.png") %>
                    <% else %>
                      <%= image_tag("star-off.png") %>
                    <% end %>
                  <% i += 1 %>
                  <% end %>
                </div>

                <div class="voting small-4 columns">
                  <%= render "votes/voting",
                      locals: {
                        review: review,
                        upvoted?: current_user && current_user.upvoted?(review),
                        downvoted?: current_user && current_user.downvoted?(review),
                      }
                  %>
                </div>
              </div>
                <div class="row">
                  <p class="review-text small-12 columns"><%= review.content %></p>
                </div>
                <% if current_user == review.user %>
                  <div class="row">
                    <p class="small-5 columns"><%= link_to "Edit", edit_parking_area_review_path(parking_area, review), class: "" %></p>
                    <p class="small-7 columns"><%= link_to "Delete", parking_area_review_path(parking_area, review), method: :delete %></p>
                  </div>
                <% end %>
              </div>
            <% end %>
          <% else %>
            <div class="review-area">
              <div class="row">
                <p class="review-text small-12 columns">No reviews yet. Be the first!</p>
              </div>
            </div>
          <% end %>
          <div class="row">
            <p class="small-12 columns"><%= link_to "New Review", new_parking_area_review_path(parking_area), method: :get %></p>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/infowindows/_show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>
    <h5><%= parking_area.title %></h5>
    <% if parking_area.verified? %>
      <h7 class="verified small-7 columns">Community Verified</h7>
    <% else %>
      <h7 class="unverified small-7 columns">Not Yet Verified</h7>
    <% end %>

    <% if verification && verification.value == 1 %>
      <p class="small-5 columns"><%= link_to "Remove Verification", parking_area_verification_path(parking_area_id: parking_area, id: verification.id), method: :patch %></p>
    <% elsif verification && verification.value == 0 %>
      <p class="small-5 columns"><%= link_to "Add Verification", parking_area_verification_path(parking_area_id: parking_area, id: verification.id), method: :patch %></p>
    <% else %>
      <p class="small-5 columns"><%= link_to "Add Verification", parking_area_verifications_path(parking_area), method: :post %></p>
    <% end %>
    <table>
      <thead>
        <tr>
          <th>Address</th>
          <th>City</th>
          <th>State</th>
          <th>Zip Code</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td><%= parking_area.address %></td>
          <td><%= parking_area.city %></td>
          <td><%= parking_area.state %></td>
          <td><%= parking_area.zip_code %></td>
        </tr>
      </tbody>
    </table>
    <p class='description-text'><%= parking_area.description %></p>

    <div class='row'>
      <p class='small-6 columns'><%= link_to 'Edit', edit_parking_area_path(parking_area) if current_user && (parking_area.user == current_user || current_user.admin) %></p>
      <p class='small-6 columns'><%= link_to 'Destroy', parking_area, method: :delete, data: { confirm: 'Are you sure?' } if current_user && (parking_area.user == current_user || curent_user.admin) %></p>
    </div>
  </body>
</html>