config/routes.rb
Rails.application.routes.draw do
  root 'parking_areas#index'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  # resources :users, only: [:show, :edit, :update]
  resources :parking_areas do
    resources :verifications, only: [:create, :update]
    resources :reviews, except: [:show, :index]
    post 'redirect_to_new_from_map', on: :collection
  end

  resources :reviews, only: [] do
    resources :comments, except: [:show, :index]
    resources :votes, only: [] do
      collection do
        post 'upvote'
        post 'downvote'
      end
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true

  validates :user_id, presence: true
  validates :value, inclusion: {in: [-1, 0, 1]}

  def upvote(user, review)
    if value == 1
      update_attributes(value: 0)
    else
      update_attributes(value: 1)
    end
  end

  def downvote(user, review)
    if value == -1
      update_attributes(value: 0)
    else
      update_attributes(value: -1)
    end
  end

  def get_initial_state
    if value == 0
      :no_vote
    elsif value == 1
      :upvoted
    else
      :downvoted
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!, :get_voteable_object, :find_or_create_vote

  def upvote
    initial_state = @vote.get_initial_state

    if @vote.upvote(current_user, @voteable)
      respond_to do |format|
        format.html { redirect_to parking_areas_path }
        format.js {
          render partial:
            'votes/upvote.js.erb',
            locals: { voteable: @voteable, initial_state: initial_state }
        }
      end
    else
      flash[:alert] = 'Error: Upvote failed to execute'
    end
  end

  def downvote
    initial_state = @vote.get_initial_state

    if @vote.downvote(current_user, @voteable)
      respond_to do |format|
        format.html { redirect_to parking_areas_path }
        format.js {
          render partial:
            'votes/downvote.js.erb',
            locals: { voteable: @voteable, initial_state: initial_state }
        }
      end
    else
      flash[:alert] = 'Error: Downvote failed to execute'
    end
  end

  private
  def get_voteable_object
    @voteable = Review.find(params[:review_id]) if params[:review_id]
  end

  def find_or_create_vote
    @vote = Vote.find_or_create_by(
      user_id: current_user.id,
      voteable_id: @voteable.id,
      voteable_type: @voteable.class
    )
  end
end

app/views/votes/_downvote.js.erb
var downvoteButton = $('#downvote-<%= voteable.id %>');
var upvoteButton = $('#upvote-<%= voteable.id %>');
var sumSelector = $('#sum-<%= voteable.id %>');
var sum = parseInt(sumSelector.html());

<% if initial_state == :no_vote %>
  sumSelector[0].innerHTML = sum - 1;
  downvoteButton.addClass('downvoted');
  downvoteButton.css('color', 'orange');
<% elsif initial_state == :downvoted %>
  sumSelector[0].innerHTML = sum + 1;
  downvoteButton.removeClass('downvoted');
  downvoteButton.css('color', '');
<% else %>
  sumSelector[0].innerHTML = sum - 2;
  upvoteButton.removeClass('upvoted');
  upvoteButton.css('color', '');
  downvoteButton.addClass('downvoted');
  downvoteButton.css('color', 'orange');
<% end %>

app/views/votes/_upvote.js.erb
var upvoteButton = $('#upvote-<%= voteable.id %>');
var downvoteButton = $('#downvote-<%= voteable.id %>');
var sumSelector = $('#sum-<%= voteable.id %>');
var sum = parseInt(sumSelector.html());

<% if initial_state == :no_vote %>
  sumSelector[0].innerHTML = sum + 1;
  upvoteButton.addClass('upvoted');
  upvoteButton.css('color', 'orange');
<% elsif initial_state == :upvoted %>
  sumSelector[0].innerHTML = sum - 1;
  upvoteButton.removeClass('upvoted');
  upvoteButton.css('color', '');
<% else %>
  sumSelector[0].innerHTML = sum + 2;
  downvoteButton.removeClass('downvoted');
  downvoteButton.css('color', '');
  upvoteButton.addClass('upvoted');
  upvoteButton.css('color', 'orange');
<% end %>

app/views/votes/_voting.html.erb
<div class="row">
  <%= link_to "⬆", upvote_review_votes_path(locals[:review]),
      id: "upvote-#{locals[:review].id}", method: :post,
      class: "small-2 columns #{'upvoted' if locals[:upvoted?]}",
      remote: true %>
  <%= content_tag :h6, locals[:review].sum_of_votes, id: "sum-#{locals[:review].id}", class: "small-2 columns" %>
  <%= link_to "⬇", downvote_review_votes_path(locals[:review]),
      id: "downvote-#{locals[:review].id}", method: :post,
      class: "small-2 columns #{'downvoted' if locals[:downvoted?]}",
      remote: true %>
</div>