config/routes.rb
Rails.application.routes.draw do
  root 'parking_areas#index'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  # resources :users, only: [:show, :edit, :update]
  resources :parking_areas do
    resources :verifications, only: [:create, :update]
    resources :reviews, except: [:show, :index]
    post 'redirect_to_new_from_map', on: :collection
  end

  resources :reviews, only: [] do
    resources :comments, except: [:show, :index]
    resources :votes, only: [] do
      collection do
        post 'upvote'
        post 'downvote'
      end
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <br>
    <div class="row">
      <div class="large-6 columns">
        <p class="footer-text">© Copyright 2016</p>
      </div>
    </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Park Easy" %></title>
    <% title %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <nav class="top-bar">
      <section class="top-bar-section">
        <div class="row">
          <h1 id="park-easy" class="small-9 medium-10 large-11 columns"><%= link_to "Park Easy", parking_areas_path, method: :get, class: "top-bar-text"%></h1>
          <button class="button small-3 medium-2 large-1 columns" type="button" data-toggle="dropdown-menu" onclick="closeMenuIfOpen(event)">MENU</button>
          <div class="dropdown-pane" id="dropdown-menu" data-dropdown data-hover="true" data-hover-pane="true">
            <% if current_user %>
              <h4 id="new"><%= link_to 'New Parking Area', new_parking_area_path, method: :get, class: "menu-options top-bar-text button" %></h4>
              <h4 id="sign-out"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "menu-options top-bar-text user_options button" %></h4>
            <% else %>
              <h4 id="new"><%= link_to 'New Parking Area', new_parking_area_path, method: :get, class: "menu-options top-bar-text button" %></h4>
              <h4 id="sign-up"><%= link_to 'Sign Up', new_user_registration_path, class: "menu-options top-bar-text user_options button" %></h4>
              <h4 id="sign-in"><%= link_to 'Sign In', new_user_session_path, class: "menu-options top-bar-text user_options button" %></h4>
            <% end %>
          </div>
        </div>
      </section>

      <a id="marker_guide_link" class="overlay-link round tiny secondary button" href="#" data-overlay-trigger>Marker Guide</a>

      <div class="overlay">
        <div class="modal">
          <h5 id="close-overlay">x</h5>
          <div class='row'>
            <%= image_tag('grey-marker.png', class: 'overlay-marker small-2 columns') %>
            <h4 class='overlay-text small-10 columns'>Unsaved</h4>
            <div class="row">
              <p class="parking-type-descriptions small-12 columns">
                A potential new parking area placed by pressing and holding the
                location on the map, or by entering the address manually
              </p>
            </div>
          </div>
          <div class='row'>
            <%= image_tag('green-marker.png', class: 'overlay-marker small-2 columns') %>
            <h4 class='overlay-text small-10 columns'>Free</h4>
            <div class="row">
              <p class="parking-type-descriptions small-12 columns">Any parking that's both free and open to anyone. EX: Visitor parking,
              free lots, etc. Does not include resident parking.</p>
            </div>
          </div>
          <div class='row'>
            <%= image_tag('blue-marker.png', class: 'overlay-marker small-2 columns') %>
            <h4 class='overlay-text small-10 columns'>Metered</h4>
            <div class="row">
              <p class="parking-type-descriptions small-12 columns">Parking with pay meters. Need we say more?</p>
            </div>
          </div>
          <div class='row'>
            <%= image_tag('yellow-marker.png', class: 'overlay-marker small-2 columns') %>
            <h4 class='overlay-text small-10 columns'>Short Term</h4>
            <div class="row">
              <p class="parking-type-descriptions small-12 columns">Any parking meant for short amounts of time. EX: fifteen minute to two hour parking.</p>
            </div>
          </div>
          <div class='row'>
            <%= image_tag('red-marker.png', class: 'overlay-marker small-2 columns') %>
            <h4 class='overlay-text small-10 columns'>Parking Garage</h4>
            <div class="row">
              <p class="parking-type-descriptions small-12 columns">Garages/lots where you can rent a spot for a pretty penny.</p>
            </div>
          </div>
          <div class='row'>
            <%= image_tag('black-marker.png', class: 'overlay-marker small-2 columns') %>
            <h4 class='overlay-text small-10 columns'>Other</h4>
            <div class="row">
              <p class="parking-type-descriptions small-12 columns">Anything else.</p>
            </div>
          </div>
        </div>
      </div>
    </nav>
      <%- flash.each do |key, value| -%>
        <div class="flash flash-<%= key %> flash-messages">
          <p class="flash-text"><%= value %></p>
        </div>
      <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>
    <%= yield :footer %>
  </body>
</html>